import type { Metadata } from 'next';
import { Roboto, Krub } from 'next/font/google';
import './globals.css';
import NavUI from '@/components/ui/navUI';

const roboto = Roboto({ subsets: ['latin'] });
const krub = Krub({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'On-gimae',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={` ${roboto.className} ${krub.className} bg-white max-w-[430px] mx-auto min-w-xs antialiased`}
      >
        {children}
        <NavUI />
      </body>
    </html>
  );
}
